version: '3.8'

services:
  # ------------------------------------------------------------
  # SERVICIO 1: BASE DE DATOS (PostgreSQL)
  # ------------------------------------------------------------
  db:
    image: postgres:15-alpine
    container_name: mrteo-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mrteodb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mrteo-network

  # ------------------------------------------------------------
  # SERVICIO 2: BACKEND (API)
  # ------------------------------------------------------------
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile # Asegúrate de tener este Dockerfile
    container_name: mrteo-api
    restart: always
    ports:
      - '3001:3001' # Puerto donde escucha tu Express
    environment:
      # OJO: Aquí 'db' es el nombre del servicio de arriba, no localhost
      DATABASE_URL: "postgresql://admin:password123@db:5432/mrteodb?schema=public"
      PORT: 3001
    depends_on:
      - db
    networks:
      - mrteo-network

  # ------------------------------------------------------------
  # SERVICIO 3: FRONTEND (App Web)
  # ------------------------------------------------------------
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile # Asegúrate de tener este Dockerfile
    container_name: mrteo-web
    restart: always
    ports:
      - '8080:80' # Mapeamos al 8080 para no chocar con otros
    depends_on:
      - api # El front depende de que la API exista
    networks:
      - mrteo-network

  # ------------------------------------------------------------
  # SERVICIO 4: pgAdmin 4 (Administrador Visual)
  # ------------------------------------------------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: mrteo-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mrteo.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - mrteo-network

networks:
  mrteo-network:
    driver: bridge

volumes:
  postgres_data:
